root<-normalizePath(file.path(dirname(sub("^--file=","",commandArgs(trailingOnly=FALSE)[grepl("^--file=",commandArgs(trailingOnly=FALSE))])),".."),winslash="/")
source(file.path(root,"lib","kegg_analysis.R"))
catalog<-data.frame(source_row=1:6,original_id=paste0("p",1:6),ncbi_gene_id=c("1","2","2","","9","99"),uniprot_accession=c("","","","U4","U9",""),gene_symbol=paste0("G",1:6),stringsAsFactors=FALSE)
ncbi<-data.frame(ncbi_gene_id=c("1","2","9","9"),kegg_gene_id=c("1","2","7","8"));uni<-data.frame(uniprot_accession="U4",kegg_gene_id="4")
m<-map_catalog_kegg(catalog,ncbi,uni,"unique-only");stopifnot(sum(m$included_in_analysis)==4,any(m$mapping_status=="ambiguous"),any(m$mapping_status=="unmapped"))
m2<-map_catalog_kegg(catalog,ncbi,uni,"all-candidates");stopifnot(sum(m2$included_in_analysis)==6)
links<-data.frame(gene_id=c("1","2","3","4","5","6","7","8"),pathway_id=c("p1","p1","p1","p2","p2","p3","p3","p3"));paths<-data.frame(pathway_id=c("p1","p2","p3"),name=c("One","Two","Three"))
f<-kegg_frequency(c("1","1","2"),links,paths);stopifnot(f$gene_count[f$pathway_id=="p1"]==2,f$gene_fraction[f$pathway_id=="p1"]==1)
e<-kegg_enrichment(c("1","2","4"),as.character(1:8),links,paths);stopifnot(nrow(e)==3,all(c("GeneRatio","BgRatio","p_value","p_adjust")%in%names(e)),all(e$p_adjust>=e$p_value))
xml<-tempfile(fileext=".xml");writeLines('<pathway><entry id="1" name="hsa:1 hsa:2" type="gene"><graphics name="A" x="10" y="20" width="30" height="40"/></entry><entry id="2" name="hsa:3" type="gene"/></pathway>',xml)
nodes<-kgml_nodes(xml,c("2"),"hsa00010");stopifnot(nrow(nodes)==2,sum(nodes$is_target_hit)==1,nodes$x[[1]]==10)
cat("R KEGG tests passed\n")
