args <- commandArgs(trailingOnly=FALSE)
file_arg <- sub("^--file=", "", args[grepl("^--file=", args)])
root <- normalizePath(file.path(dirname(file_arg), ".."), winslash="/", mustWork=TRUE)
source(file.path(root, "lib", "common.R"))
source(file.path(root, "lib", "uniprot_api.R"))
source(file.path(root, "lib", "ncbi_api.R"))
fixture <- function(name) jsonlite::read_json(file.path(root, "tests", "fixtures", name), simplifyVector=FALSE)
unique <- parse_uniprot_response(fixture("uniprot_unique.json"))
stopifnot(nrow(unique)==1, unique$uniprot_accession[[1]]=="P04637", unique$uniprot_reviewed[[1]], unique$tax_id[[1]]=="9606")
multiple <- parse_uniprot_response(fixture("uniprot_multiple.json"))
resolution <- resolve_candidate_flags(multiple, "9606")
stopifnot(nrow(multiple)==2, resolution$candidate_count==2, resolution$mapping_status=="ambiguous",
  sum(resolution$preferred_candidate)==1, resolution$preferred_candidate[[1]], any(!resolution$organism_match))
unmapped <- parse_uniprot_response(fixture("uniprot_unmapped.json"))
unmapped_resolution <- resolve_candidate_flags(unmapped, "9606")
stopifnot(nrow(unmapped)==0, unmapped_resolution$candidate_count==0, unmapped_resolution$mapping_status=="unmapped")
with_summary <- parse_ncbi_response(fixture("ncbi_with_summary.json"))
stopifnot(with_summary$ncbi_summary[[1]]=="Curated summary.", with_summary$ncbi_summary_source[[1]]=="RefSeq", with_summary$ncbi_summary_date[[1]]=="2025-01-01")
without_summary <- parse_ncbi_response(fixture("ncbi_without_summary.json"))
stopifnot(is.na(without_summary$ncbi_summary[[1]]))
cat("R parser tests passed: unique, multiple, unmapped, organism mismatch, reviewed preference, NCBI summary/source/date\n")
