args <- commandArgs(trailingOnly=FALSE)
file_arg <- sub("^--file=", "", args[grepl("^--file=", args)])
root <- normalizePath(file.path(dirname(file_arg), ".."), winslash="/", mustWork=TRUE)
source(file.path(root,"lib","presence_absence.R"))
map2 <- lapply(c("A1","A2","A3","B1","B2","B3"), function(x) list(column=x,condition=substr(x,1,1),replicate=substr(x,2,2)))
run_case <- function(a,b,threshold=0,zero=TRUE,min=2) {
  input <- as.data.frame(as.list(c(ID="P",setNames(c(a,b),c("A1","A2","A3","B1","B2","B3")))),check.names=FALSE)
  analyze_presence(input,"ID",map2,threshold,zero,"count",min,TRUE)
}
stopifnot(run_case(c(1,1,1),c(0,0,0))$classification$classification=="A-specific")
stopifnot(run_case(c(1,1,0),c(1,1,1))$classification$classification=="Shared")
stopifnot(run_case(c(1,0,0),c(0,0,0))$classification$classification=="Sporadic")
case4 <- run_case(c(1,1,1),c(1,0,0)); stopifnot(case4$classification$classification!="A-specific",case4$classification$predominant_class=="Predominantly A")
stopifnot(sum(presence_from_values(c(0,NA,1),0,TRUE))==1)
stopifnot(sum(presence_from_values(c(50,101,200),100,TRUE))==2)
unequal_map <- list(list(column="A1",condition="A"),list(column="A2",condition="A"),list(column="B1",condition="B"))
unequal <- analyze_presence(data.frame(ID="P",A1=1,A2=1,B1=1),"ID",unequal_map,0,TRUE,"fraction",1,TRUE)
stopifnot(all(unequal$detection$reproducible))
three_map <- list(list(column="A",condition="A"),list(column="B",condition="B"),list(column="C",condition="C"))
three <- analyze_presence(data.frame(ID="P",A=0,B=1,C=1),"ID",three_map,0,TRUE,"count",1,TRUE)
stopifnot(three$classification$detection_pattern=="A=0;B=1;C=1")
cat("R presence/absence tests passed: 8 cases\n")
