args <- commandArgs(trailingOnly=FALSE)
script <- sub("^--file=", "", grep("^--file=", args, value=TRUE)[1])
source(file.path(dirname(dirname(normalizePath(script))), "lib", "proteomics_qc.R"))
raw <- matrix(c(10, 20, 0, NA, 100, 200, 50, 0, 10, 20, 30, NA), nrow=4,
  dimnames=list(sprintf("ROW%06d", 1:4), c("S001", "S002", "S003")))
sample <- data.frame(sample_id=colnames(raw), column_name=c("A1","A2","B1"),
  condition=c("A","A","B"), replicate=c("1","2","1"))
feature <- data.frame(feature_id=rownames(raw), display_identifier=c("X","X","Y","Z"))
stopifnot(is.na(qc_transform(raw,"log2_positive")[3,1]))
stopifnot(qc_transform(raw,"log2p1")[3,1]==0)
stopifnot(qc_transform(raw,"none")[3,1]==0)
stopifnot(!qc_detect(raw,TRUE)[3,1], qc_detect(raw,FALSE)[3,1])
det <- qc_detect(raw,TRUE)
d <- qc_detection(det,feature,sample)
m <- qc_missingness(raw,det,feature,sample)
stopifnot(d$sample$detected_features[1]==2, m$sample$missing_fraction[1]==.5)
p <- qc_pairwise(qc_transform(raw,"none"),det,sample)
stopifnot(nrow(p$pairs)==3, p$shared[1,2]==sum(is.finite(raw[,1])&is.finite(raw[,2])))
v <- qc_cv(raw,det,feature,sample)
stopifnot(any(is.finite(v$feature$cv_percent)), all(is.na(v$feature$cv_percent[v$feature$condition=="B"])))
pca <- qc_pca(qc_transform(raw,"none"),feature,sample)
stopifnot(nrow(pca$summary)==1)
diag <- qc_diagnostics(d,m,qc_distributions(qc_transform(raw,"none"),sample),p,pca,sample)
stopifnot(nrow(diag$samples)==3)
# Exact small-number checks for pairwise-complete correlation and detection-set overlap.
known <- cbind(S1=c(1,2,3,NA,0),S2=c(2,4,6,9,0),S3=c(3,2,1,4,0))
known_sample <- data.frame(sample_id=colnames(known),condition=c("A","A","B"),replicate=c("1","2","1"))
known_pairs <- qc_pairwise(qc_transform(known,"none"),qc_detect(known,TRUE),known_sample)
stopifnot(known_pairs$shared[1,2]==4)
stopifnot(abs(known_pairs$pearson[1,2]-1)<1e-12)
stopifnot(abs(known_pairs$spearman[1,2]-1)<1e-12)
stopifnot(abs(known_pairs$jaccard[1,2]-3/4)<1e-12)
known_feature <- data.frame(feature_id=paste0("F",1:5),display_identifier=paste0("F",1:5))
known_cv <- qc_cv(known,qc_detect(known,TRUE),known_feature,known_sample)
stopifnot(abs(known_cv$feature$cv_percent[1]-100*stats::sd(c(1,2))/1.5)<1e-12)
stopifnot(is.na(known_cv$feature$cv_percent[known_cv$feature$condition=="B"][1]))
cat("Proteomics QC R unit tests passed\n")
