args<-commandArgs(trailingOnly=FALSE);root<-normalizePath(file.path(dirname(sub("^--file=","",args[grepl("^--file=",args)])),".."),winslash="/");source(file.path(root,"lib","mitocarta_analysis.R"))
tested<-0L;check<-function(value,label){if(!isTRUE(value))stop("MitoCarta R test failed: ",label);tested<<-tested+1L}
genes<-data.frame(gene_symbol=c("A","B","C","D","D","E","F"),ncbi_gene_id=c("1","2","3","4","40","5","6"),uniprot_accession=c("U1","U2","U3","U4","U40","U5","U6"),is_mitocarta=c(TRUE,TRUE,FALSE,TRUE,FALSE,FALSE,TRUE),gene_description=letters[1:7],stringsAsFactors=FALSE)
catalog<-data.frame(source_row=1:9,original_id=paste0("row",1:9),ncbi_gene_id=c("1","","","","","1","","","999"),gene_symbol=c("A","B","","D","","A","","","Z"),uniprot_accession=c("","","U3","","U1;U2","","U1","U1",""),protein_name=paste("Protein",1:9),stringsAsFactors=FALSE)
mapping<-canonical_mitocarta_mapping(catalog,genes)
check(mapping$mapping_route[mapping$source_row==1]=="NCBI Gene ID","1 NCBI mapping")
check(mapping$mapping_route[mapping$source_row==2]=="Gene symbol","2 symbol mapping")
check(mapping$mapping_route[mapping$source_row==3]=="UniProt","3 UniProt mapping")
check(mapping$mapping_route[mapping$source_row==1]=="NCBI Gene ID","4 precedence")
check(all(mapping$mapping_status[mapping$source_row==4]=="ambiguous"),"5 ambiguous symbol")
check(mapping$mapping_status[mapping$source_row==9]=="unmapped","6 unmapped")
check(!mapping$is_mitocarta[mapping$source_row==3],"7 mapped non-MitoCarta")
check(all(mapping$mapping_status[mapping$source_row==5]=="ambiguous"),"8 protein group ambiguity")
membership<-build_mitocarta_membership(mapping,genes)
check(sum(membership$canonical_gene_key=="NCBI:1")==1,"9 duplicate proteins one gene")
check(all(c("canonical_gene_key","source_rows","is_mitocarta")%in%names(membership)),"10 membership")
classification<-data.frame(source_row=1:9,classification=c("Shared","Shared","A-specific","Sporadic","Shared","Shared","A-specific","Shared","Not reproducibly detected"))
selected_rows<-classification$source_row[classification$classification=="Shared"];check(setequal(selected_rows,c(1,2,5,6,8)),"11 target selection")
background<-unique(mapping$canonical_gene_key[mapping$mapping_status=="mapped_unique"]);check(length(background)>=3,"12 background selection")
blocked<-adjust_mito_target_background(c("NCBI:1","NCBI:OUT"),c("NCBI:1"),FALSE);check(!blocked$ok&&blocked$outside=="NCBI:OUT","13 outside background")
adjusted<-adjust_mito_target_background(c("NCBI:1","NCBI:OUT"),c("NCBI:1"),TRUE);check(adjusted$ok&&identical(adjusted$target,"NCBI:1"),"14 authorized adjustment")
coverage<-mitocarta_coverage(membership,c("NCBI:1","NCBI:3"),background);check(as.numeric(coverage$value[coverage$metric=="Target MitoCarta fraction"])==0.5,"15 fraction")
overall<-overall_mitocarta_enrichment(membership,c("NCBI:1"),c("NCBI:1","NCBI:3"));check(all(overall[c("target_mitocarta","target_non_mitocarta","reference_mitocarta","reference_non_mitocarta")]==c(1,0,0,1)),"16 contingency")
check(!is.na(overall$p_value)&&overall$alternative=="greater","17 Fisher")
check(is.infinite(overall$odds_ratio),"18 infinite odds ratio")
zero_or<-overall_mitocarta_enrichment(membership,c("NCBI:3"),c("NCBI:1","NCBI:3"));check(zero_or$odds_ratio==0,"19 zero odds ratio")
sub<-data.frame(Subcompartment=c("matrix","matrix","MIM","IMS"),gene_symbol=c("A","B","B","F"),stringsAsFactors=FALSE)
target_mito<-membership[membership$canonical_gene_key%in%c("NCBI:1","NCBI:2"),];background_mito<-membership[membership$is_mitocarta,]
check(sum(sub$gene_symbol=="B")==2,"20 multiple subcompartments")
sf<-annotation_frequency(sub,target_mito,"Subcompartment");check(sf$Gene_count[sf$Subcompartment=="matrix"]==2,"21 sub frequency")
se<-annotation_enrichment(sub,target_mito,background_mito,"Subcompartment",1)$tested;check(nrow(se)>=2&&all(!is.na(se$p_value)),"22 sub enrichment")
check(isTRUE(all.equal(se$FDR,p.adjust(se$p_value,"BH"))),"23 sub BH")
paths<-data.frame(MitoPathway=c("P1","P1","P2","P3"),gene_symbol=c("A","B","B","F"),stringsAsFactors=FALSE)
pf<-annotation_frequency(paths,target_mito,"MitoPathway");check(pf$Gene_count[pf$MitoPathway=="P1"]==2,"24 pathway frequency")
hierarchy<-data.frame(MitoPathway=c("P1","P2"),pathway_full=c("Root > P1","Root > P2"),pathway_level_1="Root",stringsAsFactors=FALSE);check("pathway_full"%in%names(add_hierarchy(pf,hierarchy)),"25 hierarchy")
pe<-annotation_enrichment(paths,target_mito,background_mito,"MitoPathway",1)$tested;check(nrow(pe)>=2&&all(!is.na(pe$p_value)),"26 pathway enrichment")
minimum<-annotation_enrichment(paths,target_mito,background_mito,"MitoPathway",2);check(all(minimum$tested$Target_count>=2)&&all(minimum$excluded$Target_count<2),"27 minimum overlap")
check(isTRUE(all.equal(pe$FDR,p.adjust(pe$p_value,"BH"))),"28 pathway BH")
empty_target<-membership[FALSE,];empty_frequency<-annotation_frequency(sub,empty_target,"Subcompartment");check(nrow(empty_frequency)==0,"29 zero MitoCarta target")
check(nrow(pe[pe$FDR<0,,drop=FALSE])==0,"30 zero significant valid")
zero_background<-annotation_enrichment(sub,empty_target,empty_target,"Subcompartment",1);check(nrow(zero_background$tested)==0,"30a zero MitoCarta background")
nonhuman<-tryCatch({validate_mitocarta_organism("Mus musculus","10090");FALSE},error=function(e)grepl("Unsupported organism",e$message));check(nonhuman,"31 organism validation")
cat("R MitoCarta tests passed:",tested,"checks\n")
