args_all<-commandArgs(trailingOnly=FALSE);script_path<-normalizePath(sub("^--file=","",args_all[grepl("^--file=",args_all)]),winslash="/",mustWork=TRUE);script_root<-dirname(script_path);source(file.path(script_root,"lib","common.R"));source(file.path(script_root,"lib","kegg_analysis.R"))
required<-c("readr","jsonlite","ggplot2","openxlsx","xml2");missing<-required[!vapply(required,requireNamespace,logical(1),quietly=TRUE)];if(length(missing))stop("Missing R packages: ",paste(missing,collapse=", "))
names<-c("catalog","target-file","background-file","output","project","pathways","genes","ncbi-map","uniprot-map","gene-pathway","pathway-gene","kgml-dir","mapping-policy","fdr-cutoff","p-cutoff","min-count","top-n","run-id","snapshot-id","snapshot-manifest","snapshot-sha256","database-schema-version","organism","organism-code","tax-id","target-name","background-name","allow-target-adjustment");p<-parse_arguments(commandArgs(trailingOnly=TRUE),names)
root<-normalizePath(p$output,winslash="/",mustWork=FALSE);run<-file.path(root,"runs",p$`run-id`);snap<-file.path(p$project,"scripts","runs",paste0(p$`run-id`,"_kegg_analysis"));if(dir.exists(run)||dir.exists(snap))stop("KEGG run ID already exists.")
for(d in c("mapping","frequency","enrichment","pathways","graphs",file.path("raw",p$`run-id`),file.path("runs",p$`run-id`)))dir.create(file.path(root,d),recursive=TRUE,showWarnings=FALSE);dir.create(file.path(snap,"lib"),recursive=TRUE)
file.copy(script_path,file.path(snap,"04_kegg_analysis.R"));file.copy(file.path(script_root,"lib","kegg_analysis.R"),file.path(snap,"lib","kegg_analysis.R"));file.copy(file.path(script_root,"lib","common.R"),file.path(snap,"lib","common.R"));file.copy(p$`snapshot-manifest`,file.path(snap,"snapshot_manifest.json"));write_json(p,file.path(snap,"parameters.json"));capture.output(sessionInfo(),file=file.path(snap,"session_info.txt"))
target<-readr::read_csv(p$`target-file`,show_col_types=FALSE);background<-readr::read_csv(p$`background-file`,show_col_types=FALSE);ncbi<-readr::read_tsv(p$`ncbi-map`,show_col_types=FALSE,col_types="cc");uni<-readr::read_tsv(p$`uniprot-map`,show_col_types=FALSE,col_types="cc");links<-readr::read_tsv(p$`gene-pathway`,show_col_types=FALSE,col_types="cc");paths<-readr::read_tsv(p$pathways,show_col_types=FALSE)
tm<-map_catalog_kegg(target,ncbi,uni,p$`mapping-policy`);bm<-map_catalog_kegg(background,ncbi,uni,p$`mapping-policy`);tg<-unique(na.omit(tm$kegg_gene_id[tm$included_in_analysis]));bg<-unique(na.omit(bm$kegg_gene_id[bm$included_in_analysis]));initial_bg_size<-length(bg);outside<-setdiff(tg,bg);if(length(outside)&&p$`allow-target-adjustment`!="true")stop(length(outside)," target KEGG gene(s) are outside the selected background.");tg<-intersect(tg,bg)
freq<-kegg_frequency(tg,links,paths);enrich<-kegg_enrichment(tg,bg,links,paths);enrich$passes_min_count<-enrich$target_gene_count>=as.integer(p$`min-count`);enrich$significant<-enrich$passes_min_count&enrich$p_value<=as.numeric(p$`p-cutoff`)&enrich$p_adjust<=as.numeric(p$`fdr-cutoff`);sig<-enrich[enrich$significant,,drop=FALSE]
mapping_dir<-file.path(root,"mapping");readr::write_csv(tm,file.path(mapping_dir,"kegg_mapping.csv"));readr::write_csv(tm[tm$mapping_status=="unmapped",],file.path(mapping_dir,"kegg_unmapped.csv"));readr::write_csv(tm[tm$mapping_status=="ambiguous",],file.path(mapping_dir,"kegg_ambiguous.csv"));readr::write_csv(freq,file.path(root,"frequency/kegg_pathway_frequency.csv"));readr::write_csv(enrich,file.path(root,"enrichment/kegg_pathway_all.csv"));readr::write_csv(sig,file.path(root,"enrichment/kegg_pathway_significant.csv"))
membership<-merge(tm[tm$included_in_analysis&!is.na(tm$kegg_gene_id),],links,by.x="kegg_gene_id",by.y="gene_id");membership<-merge(membership,paths,by="pathway_id",all.x=TRUE);readr::write_csv(membership,file.path(root,"mapping/pathway_membership.csv"));raw<-file.path(root,"raw",p$`run-id`);readr::write_csv(data.frame(kegg_gene_id=tg),file.path(raw,"target_genes.csv"));readr::write_csv(data.frame(kegg_gene_id=bg),file.path(raw,"background_genes.csv"));readr::write_csv(tm,file.path(raw,"target_mapping.csv"));readr::write_csv(membership,file.path(raw,"pathway_membership_used.csv"));if(length(outside)){outside_rows<-tm[tm$kegg_gene_id%in%outside,c("kegg_gene_id","gene_symbol","original_id")];outside_rows$reason<-"Target gene is outside the selected background";readr::write_csv(outside_rows,file.path(raw,"target_outside_background.csv"))}
nodes<-lapply(unique(membership$pathway_id),function(pid)kgml_nodes(file.path(p$`kgml-dir`,paste0(pid,".xml")),tg,pid));nodes<-nodes[vapply(nodes,nrow,integer(1))>0];if(length(nodes))readr::write_csv(do.call(rbind,nodes),file.path(root,"pathways/pathway_nodes.csv"))else readr::write_csv(data.frame(),file.path(root,"pathways/pathway_nodes.csv"))
summary<-data.frame(metric=c("Experimental entities selected","Entities mapped to KEGG","Entities unmapped","Entities ambiguous","Unique KEGG genes in target","Unique KEGG genes in background","Pathways represented","Pathways tested","Pathways significant","KEGG snapshot used","Initial background definition","Initial background size","Target genes outside background","Target/background adjustment","User decision","Final background definition","Final background size","Genes removed from target"),value=c(nrow(target),sum(tm$mapping_status!="unmapped"),sum(tm$mapping_status=="unmapped"),sum(tm$mapping_status=="ambiguous"),length(tg),length(bg),nrow(freq),nrow(enrich),nrow(sig),p$`snapshot-id`,p$`background-name`,initial_bg_size,length(outside),ifelse(length(outside),"Yes","No"),ifelse(length(outside),"Continue","Not required"),p$`background-name`,length(bg),length(outside)));readr::write_csv(summary,file.path(root,"summary.csv"))
saveplot<-function(q,n){ggplot2::ggsave(file.path(root,"graphs",paste0(n,".png")),q,width=10,height=7,dpi=160);ggplot2::ggsave(file.path(root,"graphs",paste0(n,".pdf")),q,width=10,height=7)};top<-as.integer(p$`top-n`)
if(nrow(freq)){d<-head(freq,top);saveplot(ggplot2::ggplot(d,ggplot2::aes(reorder(name,gene_count),gene_count))+ggplot2::geom_col(fill="#2563EB")+ggplot2::coord_flip()+ggplot2::labs(title="KEGG Pathway Frequency",x="Pathway",y="Unique KEGG genes")+ggplot2::theme_minimal(),"kegg_pathway_frequency")}
display<-if(nrow(sig))head(sig,top)else head(enrich,top);if(nrow(display)){display$ratio<-display$target_gene_count/display$target_gene_total;title<-if(nrow(sig))"KEGG Pathway Enrichment"else"Top pathways by adjusted p-value — no significance cutoff applied to display";saveplot(ggplot2::ggplot(display,ggplot2::aes(ratio,reorder(name,ratio),size=target_gene_count,color=p_adjust))+ggplot2::geom_point()+ggplot2::labs(title=title,x="GeneRatio",y="Pathway",color="FDR (BH)")+ggplot2::theme_minimal(),"kegg_pathway_enrichment_dot")}
if(nrow(display)){display$score<--log10(pmax(display$p_adjust,.Machine$double.xmin));title<-if(nrow(sig))"KEGG Pathway Enrichment"else"Top pathways by adjusted p-value — no significance cutoff applied to display";saveplot(ggplot2::ggplot(display,ggplot2::aes(reorder(name,score),score))+ggplot2::geom_col(fill="#7C3AED")+ggplot2::coord_flip()+ggplot2::labs(title=title,x="Pathway",y="-log10(FDR)")+ggplot2::theme_minimal(),"kegg_pathway_enrichment_bar")}
wb<-openxlsx::createWorkbook();tabs<-list(Summary=summary,Mapping=tm,Unmapped=tm[tm$mapping_status=="unmapped",],Ambiguous=tm[tm$mapping_status=="ambiguous",],`Pathway membership`=membership,`Pathway frequency`=freq,`Enrichment all`=enrich,`Enrichment significant`=sig);for(n in names(tabs)){openxlsx::addWorksheet(wb,substr(n,1,31));openxlsx::writeData(wb,substr(n,1,31),tabs[[n]])};openxlsx::saveWorkbook(wb,file.path(root,"KEGG_analysis.xlsx"),overwrite=TRUE)
metadata<-list(run_id=p$`run-id`,snapshot_id=p$`snapshot-id`,snapshot_manifest_sha256=p$`snapshot-sha256`,database_schema_version=p$`database-schema-version`,organism=p$organism,organism_code=p$`organism-code`,tax_id=p$`tax-id`,mapping_policy=p$`mapping-policy`,target=p$`target-name`,background=p$`background-name`,target_outside_background=length(outside),source="Local KEGG snapshot",statistical_unit="Unique KEGG gene",enrichment_method="Hypergeometric test",p_adjust_method="Benjamini-Hochberg");write_json(metadata,file.path(run,"metadata.json"));write_json(metadata,file.path(root,"latest_metadata.json"));cat(jsonlite::toJSON(metadata,auto_unbox=TRUE),"\n")
for(folder in c("mapping","frequency","enrichment","pathways","graphs")){dir.create(file.path(run,folder),showWarnings=FALSE);file.copy(list.files(file.path(root,folder),full.names=TRUE),file.path(run,folder),overwrite=TRUE)};file.copy(file.path(root,"summary.csv"),file.path(run,"summary.csv"),overwrite=TRUE);file.copy(file.path(root,"KEGG_analysis.xlsx"),file.path(run,"KEGG_analysis.xlsx"),overwrite=TRUE)
