args_all <- commandArgs(trailingOnly=FALSE)
script_path <- normalizePath(sub("^--file=", "", args_all[grepl("^--file=", args_all)]), winslash="/", mustWork=TRUE)
script_root <- dirname(script_path)
source(file.path(script_root,"lib","common.R"));source(file.path(script_root,"lib","mitocarta_analysis.R"))
required_packages <- c("readr","jsonlite","ggplot2","openxlsx")
missing <- required_packages[!vapply(required_packages,requireNamespace,logical(1),quietly=TRUE)]
if(length(missing))stop("Missing R packages: ",paste(missing,collapse=", "))

argument_names <- c("catalog","target-file","background-file","output","project","genes","subcompartments","pathway-membership","pathway-hierarchy","run-id","snapshot-id","snapshot-manifest","snapshot-hashes","mitocarta-version","organism","tax-id","target-name","background-name","minimum-overlap","fdr-cutoff","top-n","allow-target-adjustment","mapping-policy")
p <- parse_arguments(commandArgs(trailingOnly=TRUE),argument_names);validate_mitocarta_organism(p$organism,p$`tax-id`)
root <- normalizePath(p$output,winslash="/",mustWork=FALSE);run_root<-file.path(root,"runs",p$`run-id`);provenance<-file.path(p$project,"scripts","runs",paste0(p$`run-id`,"_mitocarta"))
if(dir.exists(run_root)||dir.exists(provenance))stop("MitoCarta run ID already exists.")
folders<-c("mapping","membership","enrichment","subcompartments","mitopathways","graphs",file.path("raw",p$`run-id`));for(folder in folders)dir.create(file.path(root,folder),recursive=TRUE,showWarnings=FALSE)
dir.create(run_root,recursive=TRUE);dir.create(file.path(provenance,"lib"),recursive=TRUE)
file.copy(script_path,file.path(provenance,"06_mitocarta_analysis.R"),overwrite=FALSE);file.copy(file.path(script_root,"lib","mitocarta_analysis.R"),file.path(provenance,"lib","mitocarta_analysis.R"),overwrite=FALSE);file.copy(file.path(script_root,"lib","common.R"),file.path(provenance,"lib","common.R"),overwrite=FALSE);file.copy(p$`snapshot-manifest`,file.path(provenance,"snapshot_manifest.json"),overwrite=FALSE)
write_json(p,file.path(provenance,"parameters.json"));write_json(jsonlite::fromJSON(p$`snapshot-hashes`),file.path(provenance,"database_hashes.json"));writeLines(p$`snapshot-id`,file.path(provenance,"snapshot_id.txt"));writeLines(p$`mitocarta-version`,file.path(provenance,"mitocarta_version.txt"));capture.output(sessionInfo(),file=file.path(provenance,"session_info.txt"))

catalog<-readr::read_csv(p$catalog,show_col_types=FALSE);target_catalog<-readr::read_csv(p$`target-file`,show_col_types=FALSE);background_catalog<-readr::read_csv(p$`background-file`,show_col_types=FALSE)
genes<-readr::read_csv(p$genes,show_col_types=FALSE);sub<-readr::read_csv(p$subcompartments,show_col_types=FALSE);paths<-readr::read_csv(p$`pathway-membership`,show_col_types=FALSE);hierarchy<-readr::read_csv(p$`pathway-hierarchy`,show_col_types=FALSE)
names(sub)[names(sub)=="subcompartment"]<-"Subcompartment";names(paths)[names(paths)=="mitopathway"]<-"MitoPathway";names(hierarchy)[names(hierarchy)=="mitopathway"]<-"MitoPathway"
mapping<-canonical_mitocarta_mapping(catalog,genes);target_mapping<-canonical_mitocarta_mapping(target_catalog,genes);background_mapping<-canonical_mitocarta_mapping(background_catalog,genes);membership<-build_mitocarta_membership(mapping,genes)
target_initial<-unique(target_mapping$canonical_gene_key[target_mapping$mapping_status=="mapped_unique"]);background_initial<-unique(background_mapping$canonical_gene_key[background_mapping$mapping_status=="mapped_unique"])
if(!length(background_initial))stop("No gene-resolved entities are available in the selected background.")
adjustment<-adjust_mito_target_background(target_initial,background_initial,identical(tolower(p$`allow-target-adjustment`),"true"));record<-list(entities_outside_background=adjustment$outside,initial_target_size=length(target_initial),initial_background_size=length(background_initial),final_target_size=length(adjustment$target),final_background_size=length(adjustment$background),user_decision=if(length(adjustment$outside))if(adjustment$ok)"Continue" else "Required" else "Not required")
if(!adjustment$ok){write_json(record,file.path(root,"target_background_error.json"));write_json(record,file.path(root,"raw",p$`run-id`,"target_background_error.json"));stop("Target outside background: ",length(adjustment$outside)," canonical gene entity/entities are outside the selected background.")}
unlink(file.path(root,"target_background_error.json"),force=TRUE);target<-adjustment$target;background<-adjustment$background
target_rows<-membership[membership$canonical_gene_key%in%target,,drop=FALSE];background_rows<-membership[membership$canonical_gene_key%in%background,,drop=FALSE];target_mito<-target_rows[target_rows$is_mitocarta,,drop=FALSE];background_mito<-background_rows[background_rows$is_mitocarta,,drop=FALSE]

coverage<-mitocarta_coverage(membership,target,background);overall<-overall_mitocarta_enrichment(membership,target,background)
sub_frequency<-annotation_frequency(sub,target_mito,"Subcompartment");if(nrow(sub_frequency))sub_frequency$Fraction_of_all_target<-sub_frequency$Gene_count/max(nrow(target_rows),1)
sub_result<-annotation_enrichment(sub,target_mito,background_mito,"Subcompartment",1);sub_all<-sub_result$tested;sub_sig<-sub_all[!is.na(sub_all$FDR)&sub_all$FDR<=as.numeric(p$`fdr-cutoff`),,drop=FALSE]
path_frequency<-annotation_frequency(paths,target_mito,"MitoPathway");if(nrow(path_frequency))path_frequency$Fraction_of_all_target<-path_frequency$Gene_count/max(nrow(target_rows),1);path_frequency<-add_hierarchy(path_frequency,hierarchy)
path_result<-annotation_enrichment(paths,target_mito,background_mito,"MitoPathway",as.integer(p$`minimum-overlap`));path_all<-add_hierarchy(path_result$tested,hierarchy);path_excluded<-add_hierarchy(path_result$excluded,hierarchy);path_sig<-path_all[!is.na(path_all$FDR)&path_all$FDR<=as.numeric(p$`fdr-cutoff`),,drop=FALSE]

mapping_dir<-file.path(root,"mapping");readr::write_csv(mapping,file.path(mapping_dir,"mitocarta_mapping.csv"),na="");readr::write_csv(mapping[mapping$mapping_status=="ambiguous",],file.path(mapping_dir,"ambiguous.csv"),na="");readr::write_csv(mapping[mapping$mapping_status=="unmapped",],file.path(mapping_dir,"unmapped.csv"),na="");readr::write_csv(membership,file.path(mapping_dir,"mitocarta_membership.csv"),na="")
readr::write_csv(coverage,file.path(root,"membership","mitocarta_summary.csv"));readr::write_csv(overall,file.path(root,"enrichment","mitocarta_overall_enrichment.csv"));write_json(record,file.path(root,"enrichment","target_background_adjustment.json"))
readr::write_csv(sub_frequency,file.path(root,"subcompartments","subcompartment_frequency.csv"));readr::write_csv(sub_all,file.path(root,"subcompartments","subcompartment_enrichment_all.csv"));readr::write_csv(sub_sig,file.path(root,"subcompartments","subcompartment_enrichment_significant.csv"))
readr::write_csv(path_frequency,file.path(root,"mitopathways","mitopathway_frequency.csv"));readr::write_csv(path_all,file.path(root,"mitopathways","mitopathway_enrichment_all.csv"));readr::write_csv(path_sig,file.path(root,"mitopathways","mitopathway_enrichment_significant.csv"));readr::write_csv(path_excluded,file.path(root,"mitopathways","mitopathway_enrichment_excluded.csv"))
readr::write_csv(data.frame(canonical_gene_key=target),file.path(root,"raw",p$`run-id`,"target_genes.csv"));readr::write_csv(data.frame(canonical_gene_key=background),file.path(root,"raw",p$`run-id`,"background_genes.csv"))

status_by_row<-mapping[!duplicated(mapping$source_row),];summary<-data.frame(metric=c("Input experimental rows","Gene-resolved entities","Ambiguous entities","Unmapped entities","Target definition","Target gene count","Background definition","Background gene count","Target MitoCarta genes","Background MitoCarta genes","Target MitoCarta fraction","Background MitoCarta fraction","Overall odds ratio","Overall Fisher p-value","Subcompartments represented","Subcompartments tested","Significant subcompartments","MitoPathways represented","MitoPathways tested","Significant MitoPathways","FDR method","FDR threshold","Minimum overlap","MitoCarta version","Snapshot ID","Subcompartment membership note"),value=as.character(c(length(unique(catalog$source_row)),nrow(membership),sum(status_by_row$mapping_status=="ambiguous"),sum(status_by_row$mapping_status=="unmapped"),p$`target-name`,length(target),p$`background-name`,length(background),nrow(target_mito),nrow(background_mito),if(length(target))nrow(target_mito)/length(target)else 0,if(length(background))nrow(background_mito)/length(background)else 0,overall$odds_ratio,overall$p_value,nrow(sub_frequency),nrow(sub_all),nrow(sub_sig),nrow(path_frequency),nrow(path_all),nrow(path_sig),"Benjamini-Hochberg",p$`fdr-cutoff`,p$`minimum-overlap`,p$`mitocarta-version`,p$`snapshot-id`,"Genes may belong to multiple subcompartments; fractions can sum above 1.")),stringsAsFactors=FALSE);readr::write_csv(summary,file.path(root,"summary.csv"))

save_plot<-function(plot,name){ggplot2::ggsave(file.path(root,"graphs",paste0(name,".png")),plot,width=10,height=7,dpi=160);ggplot2::ggsave(file.path(root,"graphs",paste0(name,".pdf")),plot,width=10,height=7)}
empty_plot<-function(title,message)ggplot2::ggplot()+ggplot2::annotate("text",x=0,y=0,label=message)+ggplot2::xlim(-1,1)+ggplot2::ylim(-1,1)+ggplot2::labs(title=title)+ggplot2::theme_void();top_n<-as.integer(p$`top-n`)
composition<-data.frame(Set=rep(c("Target","Background"),each=2),Class=rep(c("MitoCarta","Non-MitoCarta"),2),Count=c(nrow(target_mito),nrow(target_rows)-nrow(target_mito),nrow(background_mito),nrow(background_rows)-nrow(background_mito)));save_plot(ggplot2::ggplot(composition,ggplot2::aes(Set,Count,fill=Class))+ggplot2::geom_col(position="stack")+ggplot2::labs(title="MitoCarta membership composition",y="Unique genes")+ggplot2::theme_minimal(),"mitocarta_membership")
frequency_plot<-function(frame,label,title){if(nrow(frame)){display<-head(frame[order(-frame$Gene_count),],top_n);ggplot2::ggplot(display,ggplot2::aes(stats::reorder(.data[[label]],Gene_count),Gene_count))+ggplot2::geom_col(fill="#2563EB")+ggplot2::coord_flip()+ggplot2::labs(title=title,x=label,y="Unique MitoCarta genes")+ggplot2::theme_minimal()}else empty_plot(title,"No represented annotations")}
dot_plot<-function(all,sig,label,title){display<-if(nrow(sig))head(sig,top_n)else head(all,top_n);plot_title<-if(nrow(sig))title else paste0(title," — exploratory display without significance cutoff");if(nrow(display))ggplot2::ggplot(display,ggplot2::aes(GeneRatio,stats::reorder(.data[[label]],GeneRatio),size=Target_count,color=FDR))+ggplot2::geom_point()+ggplot2::labs(title=plot_title,y=label,color="FDR (BH)")+ggplot2::theme_minimal()else empty_plot(plot_title,"No eligible annotations")}
save_plot(frequency_plot(sub_frequency,"Subcompartment","Sub-mitochondrial compartment frequency"),"subcompartment_frequency");save_plot(frequency_plot(path_frequency,"MitoPathway","Top MitoPathways by frequency"),"mitopathway_frequency");save_plot(dot_plot(sub_all,sub_sig,"Subcompartment","Subcompartment enrichment"),"subcompartment_enrichment");save_plot(dot_plot(path_all,path_sig,"MitoPathway","MitoPathway enrichment"),"mitopathway_enrichment")

workbook<-openxlsx::createWorkbook();tabs<-list(Summary=summary,Mapping=mapping,Membership=membership,Unmapped=mapping[mapping$mapping_status=="unmapped",],Ambiguous=mapping[mapping$mapping_status=="ambiguous",],`Overall enrichment`=overall,`Subcompartment frequency`=sub_frequency,`Subcompartment enrichment`=sub_all,`MitoPathway frequency`=path_frequency,`MitoPathway enrichment`=path_all,`MitoPathway excluded`=path_excluded)
for(name in names(tabs)){openxlsx::addWorksheet(workbook,name);openxlsx::writeData(workbook,name,tabs[[name]])};openxlsx::saveWorkbook(workbook,file.path(root,"MitoCarta_analysis.xlsx"),overwrite=TRUE)
metadata<-list(run_id=p$`run-id`,snapshot_id=p$`snapshot-id`,mitocarta_version=p$`mitocarta-version`,organism=p$organism,tax_id=p$`tax-id`,target_definition=p$`target-name`,background_definition=p$`background-name`,mapping_policy=p$`mapping-policy`,minimum_overlap=as.integer(p$`minimum-overlap`),fdr_threshold=as.numeric(p$`fdr-cutoff`),fdr_method="Benjamini-Hochberg",overall_test="Fisher exact test; alternative greater; target versus background outside target",statistical_unit="Unique canonical gene",source="Local MitoCarta3.0 snapshot",network_access=FALSE,target_background_adjustment=record)
write_json(metadata,file.path(run_root,"metadata.json"));write_json(metadata,file.path(root,"latest_metadata.json"));for(folder in c("mapping","membership","enrichment","subcompartments","mitopathways","graphs")){destination<-file.path(run_root,folder);dir.create(destination,recursive=TRUE);file.copy(list.files(file.path(root,folder),full.names=TRUE),destination,overwrite=TRUE)};dir.create(file.path(run_root,"raw"));file.copy(list.files(file.path(root,"raw",p$`run-id`),full.names=TRUE),file.path(run_root,"raw"),overwrite=TRUE);file.copy(file.path(root,"summary.csv"),file.path(run_root,"summary.csv"),overwrite=TRUE);file.copy(file.path(root,"MitoCarta_analysis.xlsx"),file.path(run_root,"MitoCarta_analysis.xlsx"),overwrite=TRUE);write_json(metadata,file.path(provenance,"run_metadata.json"));cat(jsonlite::toJSON(metadata,auto_unbox=TRUE),"\n")
